<?php
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Penduduk;
use Illuminate\Support\Facades\DB;

$output = "--- Simulation Test ---\n";

try {
    echo "Attempting to create a test resident...\n";
    $p = new Penduduk();
    $p->nik = '1234567890123456';
    $p->nama = 'Test Resident';
    $p->jenis_kelamin = 'L';
    $p->status = 'aktif';
    // nik_hash should be auto-generated by trait
    $p->save();

    $output .= "SUCCESS: Resident created. ID: " . $p->id . "\n";
    $p->delete(); // Clean up
}
catch (\Exception $e) {
    $output .= "ERROR: " . $e->getMessage() . "\n";
}

file_put_contents('simulation_test_results.txt', $output);
echo "Simulation complete. Results in simulation_test_results.txt\n";
